### ISSUE TITLE
Does this need to be updated?

### ISSUE THREAD

**Issue by ghost** [evgeniyp/vscode-dark-low-contrast#2]
I really love your theme and think it is the BEST in the market. This is not an issue but just a question. Since I know little about how the color themes work, I'm curious about that if VSCode adds support to a new language, does it needs also to implement the corresponding color theme for that language? If it is the case then the other custom color themes seem also need to be updated.

**Comment by evgeniyp** [comment]
It's not a matter of a new programming language, but of a new token type, like it's described here:
https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting

AFAIK there were no new tokens for a long time, and in case of VS Code introduces them, we will know about it from the changelog

**Comment by ghost** [comment]
Thanks for the reply!
